site_name: Avatar Scene Browser
site_description: Unity化身场景管理插件文档
site_author: Cynth-mt
site_url: https://cynth-mt.github.io/

repo_name: cynth-mt/cynth-mt.github.io
repo_url: https://github.com/cynth-mt/cynth-mt.github.io
edit_uri: edit/main/AvatarSceneBrowser/docs/

theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    # 亮色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    # 暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  features:
    # 导航功能
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    # 搜索功能
    - search.highlight
    - search.share
    - search.suggest
    # 目录功能
    - toc.follow
    - toc.integrate
    # 内容功能
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # 页脚导航
    - navigation.footer

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: 
        - zh
        - ja
        - en
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

markdown_extensions:
  # 代码高亮
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
  # 标签页和详情
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details
  
  # 提示框
  - admonition
  - pymdownx.blocks.admonition:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
  
  # 任务列表和键盘按键
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  
  # 数学公式
  - pymdownx.arithmatex:
      generic: true
  
  # 表情符号和图标
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  # 其他扩展
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  
  # 目录
  - toc:
      permalink: true
      permalink_title: 锚点链接
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

nav:
  - 主页: index.md
  - 开始使用: getting-started.md
  - 用户指南:
    - 安装指南: installation.md
    - 基本配置: configuration.md
    - 使用方法: usage.md
  - 功能模块:
    - 化身管理: avatar-management.md
    - 场景浏览: scene-browsing.md
    - 运行时API: runtime-api.md
  - 高级功能:
    - 扩展开发: extension-development.md
    - 性能优化: performance.md
    - 集成第三方资源: integration.md
  - 开发文档:
    - API参考: api-reference.md
    - 示例代码: examples.md
    - 单元测试: unit-testing.md
  - 常见问题: faq.md
  - 更新日志: changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cynth-mt
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cynth_mt
      name: Twitter
  analytics:
    feedback:
      title: 这个页面有帮助吗？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 这个页面很有帮助
          data: 1
          note: >-
            感谢您的反馈！
        - icon: material/emoticon-sad-outline
          name: 这个页面可以改进
          data: 0
          note: >-
            感谢您的反馈！请通过GitHub Issues告诉我们如何改进。
  generator: false
  version:
    provider: mike

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

copyright: |
  Copyright &copy; 2023-present <a href="https://github.com/cynth-mt" target="_blank" rel="noopener">Cynth-mt</a> –
  <a href="#__consent">更改cookie设置</a> 