site_name: Avatar Scene Browser
site_description: Unity化身场景管理插件文档
site_author: Cynth-mt
site_url: https://cynth-mt.github.io/AvatarSceneBrowser/
use_directory_urls: true

repo_name: cynth-mt/cynth-mt.github.io
repo_url: https://github.com/cynth-mt/cynth-mt.github.io
edit_uri: edit/main/AvatarSceneBrowser/docs/

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.annotate
    - content.code.copy

plugins:
  - search:
      lang: ja
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - 主页: index.md
  - 开始使用: getting-started.md
  - 用户指南:
    - 安装指南: installation.md
    - 基本配置: configuration.md
    - 使用方法: usage.md
  - 功能模块:
    - 场景浏览: scene-browsing.md
    - 运行时API: runtime-api.md
  - 常见问题: faq.md
  - 更新日志: release_log.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cynth-mt
  generator: false 

#copyright: Copyright &copy; 2023-present Cynth-mt

# Force rebuild - trigger workflow 20250120